apiVersion: apps/v1
kind: Deployment
metadata:
 name: docker
 namespace: mydocker1
spec:
 strategy:
   type: Recreate
 selector:
   matchLabels:
     app: docker
 replicas: 1
 template:
   metadata:
     labels:
       app: docker
   spec:
     containers:
     - name: mydocker
       image: vbrilik/docker_test:speedtest
       ports:
       - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
 name: docker
 namespace: mydocker1
 labels:
   app: docker
spec:
 externalTrafficPolicy: Local
 ports:
 - name: http
   port: 80
   protocol: TCP
   targetPort: 80
 selector:
   app: docker
 type: NodePort
