version: '2.2'
services:
  web:
    container_name: web
    restart: always
    image: aspendigital/octobercms:latest
    ports:
      - 8089:80
    environment:
      - DB_TYPE=mysql
      - DB_HOST=db #DB_HOST should match the service name of the database container
      - DB_DATABASE=octobercms
      - DB_USERNAME=octobercms
      - DB_PASSWORD=local
    volumes:
      - $HOME/project_octobercms/plugins:/var/www/html/plugins
      - $HOME/project_octobercms/storage/app:/var/www/html/storage/app
      - $HOME/project_octobercms/storage/logs:/var/www/html/storage/logs
      - $HOME/project_octobercms/themes:/var/www/html/themes

  db:
    image: mariadb
    container_name: db
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: octobercms
      MYSQL_USER: octobercms
      MYSQL_PASSWORD: local
    volumes:
       - $HOME/project_octobercms/volumes/mysql/data:/var/lib/mysql
       - $HOME/project_octobercms/backup:/home/backup
