---

- name: postgresql
  hosts: all
  become: yes

  tasks:

    - name: Install dependencies for PostgreSQL
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'bash', 'openssl', 'libssl-dev', 'libssl-doc']
  
    - name: Install PostgreSQL 
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'postgresql', 'postgresql-contrib', 'libpq-dev', 'python3-psycopg2']

    - name: Ensure the PostgreSQL service is running
      service: name=postgresql state=started enabled=yes
      environment: 
        POSTGRES_HOST_AUTH_METHOD: 'trust'
