- hosts: all
  gather_facts: true
    
  tasks:

  - name: Create group "devops"
    ansible.builtin.group:
      name: devops
      state: present
      gid: 1400
    become: yes

  - name: Add user "belhard"
    ansible.builtin.user:
      name: belhard
      group: devops
      shell: /bin/bash
      comment: "Belhard DevOps user"
      state: present
      uid: 1500
    become: yes
  - name: Install curl, wget, unzip, zip
    apt:
      update_cache: yes
      pkg:
      - curl
      - wget
      - zip
      - unzip
      autoclean: yes
      autoremove: yes
    become: yes

  - name: install java to ansible_1
    apt:
      update_cache: yes
      pkg:
      - openjdk-11-jdk
      autoclean: yes
      autoremove: yes
    when:
      - ansible_hostname == "ansible-1"
    become: yes

  - name: install nginx to ansible_2
    apt:
      update_cache: yes
      pkg:
      - nginx
      autoclean: yes
      autoremove: yes
    when:
      - ansible_hostname == "ansible-2"
    become: yes

