---

- name: Setting up my VMs
  gather_facts: true
  hosts: all

  tasks:

    - name: Create docker directory
      file:
        path: /home/belhard/docker
        state: directory
        owner: belhard
        group: devops
      become: yes

    - name: Create docker directory
      file:
        path: /home/belhard/docker/docker_test
        state: directory
        owner: belhard
        group: devops
      when:
        - ansible_hostname == 'ansible-1'
      become: yes

    - name: Copy docfile with owner and permission
      ansible.builtin.copy:
        src: /home/vagrant/ansible/docker/docker/Dockerfile
        dest: /home/belhard/docker/Dockerfile
        owner: belhard
        group: devops
        mode: u=rw,g=rw,o=r
      when:
        - ansible_hostname == 'ansible-1'
      become: yes

    - name: Copy docfile with owner and permission
      ansible.builtin.copy:
        src: /home/vagrant/ansible/docker/docker/entrypoint.sh
        dest: /home/belhard/docker/entrypoint.sh
        owner: belhard
        group: devops
        mode: u=rwx,g=rwx,o=r
      when:
        - ansible_hostname == 'ansible-1'
      become: yes

    - name: Create nginx1 directory
      file:
        path: /home/belhard/docker/nginx1
        state: directory
        owner: belhard
        group: devops
      when:
        - ansible_hostname == 'ansible-2'
      become: yes

    - name: Create nginx2 directory
      file:
        path: /home/belhard/docker/nginx2
        state: directory
        owner: belhard
        group: devops
      when:
        - ansible_hostname == 'ansible-2'
      become: yes

    - name: Copy docfile and index.html with owner and permission
      ansible.builtin.copy:
        src: /home/vagrant/ansible/docker/nginx1/
        dest: /home/belhard/docker/nginx1/
        owner: belhard
        group: devops
        mode: u=rw,g=rw,o=r
      when:
        - ansible_hostname == 'ansible-2'
      become: yes


    - name: Copy docfile and index.html with owner and permission
      ansible.builtin.copy:
        src: /home/vagrant/ansible/docker/nginx2/
        dest: /home/belhard/docker/nginx2/
        owner: belhard
        group: devops
        mode: u=rw,g=rw,o=r
      when:
        - ansible_hostname == 'ansible-2'
      become: yes
