---

- name: backup DB
  gather_facts: true
  hosts: all
  become: yes

  tasks:


    - name: Copy output_file_old ansible 1 host
      fetch:
        src: /home/belhard/docker/postgres3/dump/old_request
        dest: /home/vagrant/ansible/postgres3/ans1/
        flat: yes
      become: yes
      when:
        - ansible_hostname == 'ansible-1'

    - name: Copy output_file_new ansible 2 host
      fetch:
        src: /home/belhard/docker/postgres3/dump/new_request
        dest: /home/vagrant/ansible/postgres3/ans2/
        flat: yes
      become: yes
      when:
        - ansible_hostname == 'ansible-2'
