---

- name: backup DB
  gather_facts: true
  hosts: all
  become: yes
  vars:
    container_name1: my_docker_1_old
    image_name1: my_image_1_old
    tag_name1: my_tag_1_old
    container_name2: my_docker_2_new
    image_name2: my_image_2_new
    tag_name2: my_tag_2_new
    image_dockerfile: /home/belhard/docker/postgres3/Dockerfile
    image_path: /home/belhard/docker/postgres3

  tasks:

    - name: create Docker image
      command: docker build {{ image_path }} -f {{ image_dockerfile }} -t {{ image_name1 }}:{{ tag_name1 }}

    - name: Create and start container
      docker_container:
        name: "{{ container_name1 }}"
        image: "{{ image_name1 }}:{{ tag_name1 }}"
        volumes:
          - /home/belhard/docker/postgres3/dump:/dump
      when:
        - ansible_hostname == 'ansible-1'

    - name: create Docker image
      command: docker build {{ image_path }} -f {{ image_dockerfile }} -t {{ image_name2 }}:{{ tag_name2 }}

    - name: Create and start container
      docker_container:
        name: "{{ container_name2 }}"
        image: "{{ image_name2 }}:{{ tag_name2 }}"
        volumes:
          - /home/belhard/docker/postgres3/dump:/dump
      when:
        - ansible_hostname == 'ansible-2'
