---

- name: Setting up my VMs
  gather_facts: true
  hosts: all

  tasks:

    - name: install packages
      apt:
        update_cache: yes
        pkg:
        - unzip
        - zip
        - curl
        - wget
      become: yes
