---

- name: Setting up my VMs
  gather_facts: true
  hosts: all

  tasks:

    - name: Create group "devops"
      ansible.builtin.group:
        name: devops
        state: present
        gid: 1100
      become: yes

    - name: Add user "belhard"
      ansible.builtin.user:
        name: belhard
        group: devops
        shell: /bin/bash
        comment: "Belhard DevOps user"
        state: present
        uid: 1200
      become: yes

    - name: install packages
      apt:
        update_cache: yes
        pkg:
        - unzip
        - zip
        - curl
        - wget
      become: yes


    - name: install java
      apt:
        update_cache: yes
        pkg:
        - openjdk-11-jdk
        autoclean: yes
        autoremove: yes
      when:
        - ansible_hostname == 'ansible-1'
      become: yes

    - name: Install Nginx
      apt: name=nginx state=latest
      when:
        - ansible_hostname == 'ansible-2'
      become: yes
      notify:
        - restart nginx

  handlers:
    - name: restart nginx
      service: name=nginx state=reloaded
      become: yes
