---

- name: backup DB
  gather_facts: true
  hosts: all
  become: yes
  vars:
    container_name1: my_docker_old
    image_name1: my_image_old
    tag_name1: my_tag_old
    container_name2: my_docker_new
    image_name2: my_image_new
    tag_name2: my_tag_new
    image_dockerfile: /home/belhard/docker/postgres2/Dockerfile
    image_path: /home/belhard/docker/postgres2

  tasks:

    - name: Create postgres directory
      file:
        path: /home/belhard/docker/postgres2
        state: directory
        owner: belhard
        group: devops
        mode: u=rwx,g=rwx,o=rx
      become: yes

    - name: Create dump directory
      file:
        path: /home/belhard/docker/postgres2/dump
        state: directory
        owner: belhard
        group: devops
        mode: u=rwx,g=rwx,o=rx
      become: yes

    - name: Copy dockerfile with owner and permission
      ansible.builtin.copy:
        src: /home/vagrant/ansible/short_playbooks/Dockerfile
        dest: /home/belhard/docker/postgres2/Dockerfile
        owner: belhard
        group: devops
        mode: u=rw,g=rw,o=r
      become: yes


    - name: Copy script with owner and permission
      ansible.builtin.copy:
        src: /home/vagrant/ansible/short_playbooks/sc.sh
        dest: /home/belhard/docker/postgres2/dump/sc.sh
        owner: belhard
        group: devops
        mode: u=rwx,g=rwx,o=r
      become: yes

    - name: Copy create script with owner and permission
      ansible.builtin.copy:
        src: /home/vagrant/ansible/short_playbooks/create.sh
        dest: /home/belhard/docker/postgres2/dump/create.sh
        owner: belhard
        group: devops
        mode: u=rwx,g=rwx,o=r
      become: yes

    - name: Copy recreate script with owner and permission
      ansible.builtin.copy:
        src: /home/vagrant/ansible/short_playbooks/recreate.sh
        dest: /home/belhard/docker/postgres2/dump/recreate.sh
        owner: belhard
        group: devops
        mode: u=rwx,g=rwx,o=r
      become: yes


    - name: create Docker image
      command: docker build {{ image_path }} -f {{ image_dockerfile }} -t {{ image_name1 }}:{{ tag_name1 }}

    - name: Create and start container
      docker_container:
        name: "{{ container_name1 }}"
        image: "{{ image_name1 }}:{{ tag_name1 }}"
        volumes:
          - /home/belhard/docker/postgres2/dump:/dump

    - name: create Docker image
      command: docker build {{ image_path }} -f {{ image_dockerfile }} -t {{ image_name2 }}:{{ tag_name2 }}

    - name: Create and start container
      docker_container:
        name: "{{ container_name2 }}"
        image: "{{ image_name2 }}:{{ tag_name2 }}"
        volumes:
          - /home/belhard/docker/postgres2/dump:/dump

    - name: run script image
      command: sh /home/belhard/docker/postgres2/dump/sc.sh
    - name: Copy output_file_old ansible 1 host
      fetch:
        src: /home/belhard/docker/postgres2/dump/old_request
        dest: /home/vagrant/ansible/short_playbooks/ans1/
        flat: yes
      become: yes
      when:
        - ansible_hostname == 'ansible-1'

    - name: Copy output_file_new ansible 1 host
      fetch:
        src: /home/belhard/docker/postgres2/dump/new_request
        dest: /home/vagrant/ansible/short_playbooks/ans1/
        flat: yes
      become: yes
      when:
        - ansible_hostname == 'ansible-1'

    - name: Copy output_file_old ansible 2 host
      fetch:
        src: /home/belhard/docker/postgres2/dump/old_request
        dest: /home/vagrant/ansible/short_playbooks/ans2/
        flat: yes
      become: yes
      when:
        - ansible_hostname == 'ansible-2'

    - name: Copy output_file_new ansible 2 host
      fetch:
        src: /home/belhard/docker/postgres2/dump/new_request
        dest: /home/vagrant/ansible/short_playbooks/ans2/
        flat: yes
      become: yes
      when:
        - ansible_hostname == 'ansible-2'

