---

- name: backup DB
  gather_facts: true
  hosts: all
  become: yes
  vars:
    container_name1: my_docker_1_old
    image_name1: my_image_1_old
    tag_name1: my_tag_1_old
    container_name2: my_docker_2_new
    image_name2: my_image_2_new
    tag_name2: my_tag_2_new
    image_dockerfile: /home/belhard/docker/postgres3/Dockerfile
    image_path: /home/belhard/docker/postgres3

  tasks:

    - name: Create postgres directory
      file:
        path: /home/belhard/docker/postgres3
        state: directory
        owner: belhard
        group: devops
        mode: u=rwx,g=rwx,o=rx
      become: yes

    - name: Create dump directory
      file:
        path: /home/belhard/docker/postgres3/dump
        state: directory
        owner: belhard
        group: devops
        mode: u=rwx,g=rwx,o=rx
      become: yes

    - name: Copy dockerfile with owner and permission
      ansible.builtin.copy:
        src: /home/vagrant/ansible/short_playbooks/Dockerfile
        dest: /home/belhard/docker/postgres3/Dockerfile
        owner: belhard
        group: devops
        mode: u=rw,g=rw,o=r
      become: yes


    - name: Copy script with owner and permission
      ansible.builtin.copy:
        src: /home/vagrant/ansible/short_playbooks/sc_create.sh
        dest: /home/belhard/docker/postgres3/dump/sc_create.sh
        owner: belhard
        group: devops
        mode: u=rwx,g=rwx,o=r
      become: yes
      when:
        - ansible_hostname == 'ansible-1'

    - name: Copy script with owner and permission
      ansible.builtin.copy:
        src: /home/vagrant/ansible/short_playbooks/sc_recreate.sh
        dest: /home/belhard/docker/postgres3/dump/sc_recreate.sh
        owner: belhard
        group: devops
        mode: u=rwx,g=rwx,o=r
      become: yes
      when:
        - ansible_hostname == 'ansible-2'

    - name: Copy create script with owner and permission
      ansible.builtin.copy:
        src: /home/vagrant/ansible/short_playbooks/create1.sh
        dest: /home/belhard/docker/postgres3/dump/create1.sh
        owner: belhard
        group: devops
        mode: u=rwx,g=rwx,o=r
      become: yes
      when:
        - ansible_hostname == 'ansible-1'

    - name: Copy recreate script with owner and permission
      ansible.builtin.copy:
        src: /home/vagrant/ansible/short_playbooks/recreate1.sh
        dest: /home/belhard/docker/postgres3/dump/recreate1.sh
        owner: belhard
        group: devops
        mode: u=rwx,g=rwx,o=r
      become: yes
      when:
        - ansible_hostname == 'ansible-2'


    - name: create Docker image
      command: docker build {{ image_path }} -f {{ image_dockerfile }} -t {{ image_name1 }}:{{ tag_name1 }}

    - name: Create and start container
      docker_container:
        name: "{{ container_name1 }}"
        image: "{{ image_name1 }}:{{ tag_name1 }}"
        volumes:
          - /home/belhard/docker/postgres3/dump:/dump
      when:
        - ansible_hostname == 'ansible-1'

    - name: create Docker image
      command: docker build {{ image_path }} -f {{ image_dockerfile }} -t {{ image_name2 }}:{{ tag_name2 }}

    - name: Create and start container
      docker_container:
        name: "{{ container_name2 }}"
        image: "{{ image_name2 }}:{{ tag_name2 }}"
        volumes:
          - /home/belhard/docker/postgres3/dump:/dump
      when:
        - ansible_hostname == 'ansible-2'

    - name: run script image
      command: sh /home/belhard/docker/postgres3/dump/sc_create.sh
      when:
        - ansible_hostname == 'ansible-1'

    - name: Copy backup from ansible 1 host to localhost
      fetch:
        src: /home/belhard/docker/postgres3/dump/dumpfull
        dest: /home/vagrant/ansible/short_playbooks/
        flat: yes
      become: yes
      when:
        - ansible_hostname == 'ansible-1'

    - name: Copy backup t0 ansible2 with owner and permission
      ansible.builtin.copy:
        src: /home/vagrant/ansible/short_playbooks/dump/dumpfull
        dest: /home/belhard/docker/postgres3/dump/dumpfull
        owner: belhard
        group: devops
        mode: u=rw,g=rw,o=r
      become: yes
      when:
        - ansible_hostname == 'ansible-2'

    - name: run script image
      command: sh /home/belhard/docker/postgres3/dump/sc_recreate.sh
      when:
        - ansible_hostname == 'ansible-2'

    - name: Copy output_file_old ansible 1 host
      fetch:
        src: /home/belhard/docker/postgres3/dump/old_request
        dest: /home/vagrant/ansible//dump/ans11/
        flat: yes
      become: yes
      when:
        - ansible_hostname == 'ansible-1'

    - name: Copy output_file_new ansible 2 host
      fetch:
        src: /home/belhard/docker/postgres3/dump/new_request
        dest: /home/vagrant/ansible//dump/ans12/
        flat: yes
      become: yes
      when:
        - ansible_hostname == 'ansible-2'
